<?php
/**
 * Copyright (C) EC Brands Corporation - All Rights Reserved
 * Contact Licensing@ECInternet.com for use guidelines
 */
declare(strict_types=1);
?>

<?php /** @var \ECInternet\Pricing\Block\Catalog\Product\View $block */ ?>

<div class="ecinternet_custom_price">
    <?= $block->getCustomPriceHtml() ?>
</div>

<style>
    .ecinternet_custom_price {
        font-size: 36px;
        line-height: 36px;
    }
</style>
